config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 300}
  validates :user_id, presence: true
  
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
            
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105},
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "Você precisa estar conectado para acessar essas funções"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @article = Article.new
  end

  def edit
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if (@article.save)
      flash[:success] = "O artigo foi criado com sucesso"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if (@article.update(article_params))
      flash[:success] = "O artigo foi editado com sucesso"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "O artigo foi apagado com sucesso"
    redirect_to articles_path
  end
  
  private
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "Somente o autor desse artigo pode alterá-lo."
        redirect_to root_path
      end
    end
    
    def set_article
      @article = Article.find(params[:id])  
    end
    
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "A categoria foi criada com sucesso"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "A categoria foi editada com sucesso"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? or (logged_in? and !current_user.admin?)
      flash[:danger] = "Somente administradores podem criar ou alterar categorias"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Você se conectou com êxito."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Houve um erro com os seus dados de autenticação."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Você se desconectou com êxito."
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if (@user.save)
      session[:user_id] = @user.id
      flash[:success] = "O usuário foi criado com sucesso, Bem vindo, #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Sua conta foi atualizada"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "Esse usuário e todos os seus artigos foram deletados."
    redirect_to users_path
  end
  
  private
    
    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "Somente o dono dessa conta pode alterar os dados cadastrais dela."
        redirect_to root_path
      end      
    end
    
    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Somente o administrador pode remover usuários do sistema."
        redirect_to root_path
      end
    end
    
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>      
        </div>
        <div class="article-body">
          <%= truncate(article.description, lenght:50) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user%>,
                   <%= time_ago_in_words(article.created_at) %> ago,
                   last updated: <%= time_ago_in_words(article.updated_at) %> ago.</small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categorias: <%= render article.categories %></p>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?)%>
          <div class="article-actions">
            <%= link_to 'Edite esse artigo', edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Apague esse artigo', article_path(article), method: :delete,
                        data: { confirm: "Tem certeza de que quer apagar esse artigo?"},
                        class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :titulo %>  
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Título do artigo", autofocus: true %>
      </div>    
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :conteudo %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, class: "form-control", rows: 6, placeholder: "Conteúdo do artigo"%>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg"%>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      <%= link_to 'Cancelar e voltar para os artigos', articles_path, class:"btn btn-primary btn-sm" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Editar o artigo </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Todos os artigos</h1>
<div align = "center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align = "center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Escrever um novo artigo </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align= "center"><%= @article.title %><h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class = "listing">
      <div class = "row center">
        <div class = "col-md-4 col-md-offset-4">
          <li>Por</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class = "article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
            <li ><small>
            <%= pluralize(@article.user.articles.count, "artigo") if
                          @article.user.articles %>
            </small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Conteúdo:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categorias: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edita esse artigo', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to 'Apagar esse artigo', article_path(@article), method: :delete,
                    data: { confirm: "Tem certeza que quer apagar esse artigo?"},
                    class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to 'Ver todos os artigos', articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :nome %>  
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Nome do categoria", autofocus: true %>
    </div>    
  </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
  <%= link_to 'Cancelar e voltar para os artigos', articles_path, class:"btn btn-primary btn-sm" %>
</div>

app/views/categories/edit.html.erb
<h1 align="center"> Editar a categoria </h1>

<%= render 'form' %> 

app/views/categories/index.html.erb
<h1 align = "center">Categorias</h1>
<div align = "center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 well col-md-offset-4">
          <li class="article-title"><%= link_to "#{category.name}",
                                        category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "artigo")%></small></li>
        </div>
      </div>
    </ul>  
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Criar nova categoria</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align = "center"><%= "Categoria: " + @category.name %></h1>
<div align = "center">
  <% if logged_in? and current_user.admin? %>
    <div class = "row">
      <span class = "badge"><%= link_to "Alterar o nome da categoria", edit_category_path(@category)%></span> 
    </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category.articles %>

<div align = "center">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright &copy; <a href="http://google.com">Rafael Prallon</a>. 
           Made with <a href="http://rubyonrails.org"> Ruby on Rails</a> and 
           <a href="http://getbootstrap.com">Bootstrap 3</a>.</small>
    <small> Respeite as leis locais.</small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg|%>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alfa Blog", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Artigos", articles_path %></li>
        <li><%= link_to "Usuários", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-haspopup="true" aria-expanded="false">Ações <span class="caret">
            </span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Criar novo artigo", new_article_path%></li>
              <li><a href="#">Criar um novo usuário</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
          aria-haspopup="true" aria-expanded="false">Categorias <span class="caret">
          </span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Todas as categorias", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? and current_user.admin?%>
            <li role="separator" class="divider"></li>
              <li><%= link_to "Criar nova categoria", new_category_path %></li>
            <% end %>
          </ul>
          </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
            aria-haspopup="true" aria-expanded="false"> Seu perfil <%= "Administrador" if current_user.admin? %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Alterar dados", edit_user_path(current_user) %></li>
              <li><%= link_to "Visualizar perfil", user_path(current_user)%></li>
              <li><%= %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
        <% end%>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlfaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>  
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  
</body>
</html>

app/views/pages/about.html.erb
<title>Home - Alfa Blog</title>
  <meta charset='utf-8'>
  <style>
    .container1, .container2, .container3{
      float: inherit;
	    display: inline-block;
	    background-color: lightblue;
	    color: black;
	    width: 30%;
	    border: 1px dashed black;
	    text-align: left;  
    }
    #header{
      background-image: url(https://unsplash.it/1700/800/?random);
	    background-size: cover;
	    color: white;
	    border-radius: 20px;
	    box-shadow: 1px 1px 2px 3px, rgb(230,230,230);
	    font-size: 70;
	    text-align: center;
    }
    footer{
      font-family: verdana;
      font-size: 1em;
    }
  </style>
</head>
<body>
  <div id='header'>
    <h1>Welcome to the Alfa Blog's about page. Here you'll understand it's features<h1>
  </div>
  <div class='container1'>
		<h2>Feature 1</h2>
		<p>Details of the feature</p>
	</div>
	<div class='container2'>
		<h2>Feature 2</h2>
		<p>Details of the feature</p>
	</div>
	<div class='container3'>
		<h2>Feature 3</h2>
		<p>Details of the feature</p>
	</div>
	<h2>To use it, go <%= link_to 'here', root_path %></h2>
</body>
<footer>
  <p>Here you'll see the trademarks and stuff</p>
</footer>

app/views/pages/home.html.erb
<head>
  <style>
    .container1, .container2{
      float: inherit;
	    display: inline-block;
	    background-color: lightblue;
	    color: black;
	    width: 49%;
	    height: 500px%;
	    border: 1px solid black;
	    text-align: left;
	    margin: 2px;
    }
    a:hover{
    	text-decoration: none;
    }
	</style>
</head>
<body>
  <div class='center jumbotron'>
    <h1>Welcome to the Alfa Blog. Here you'll be able to read great stories for anyone in the world<h1>
  	<h2><%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg btn-xlarge"%></h2>
	<h2>To see the post, go <%= link_to 'here', articles_path %></h2>
  </div>
  <div class='container1'>
		<h2>Escreva sobre o que você quiser</h2>
		<p>Aqui não há restrições sobre os assuntos a serem tratados.*</p>
	</div>
	<div class='container2'>
		<h2>Leia os artigos dos mais variados autores</h2>
		<p>Aqui todas as vozes são ouvidas e respeitadas</p>
	</div>
</body>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "erro")%> preveniram a execução da operação pedida.
            </h2>
          <div class="panel-body">
             <ul>
                <% obj.errors.full_messages.each do |msg|%>
                  <li><%= msg %></li>
                <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :nome %>  
      </div>
      <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Nome do usuário", autofocus: true %>
      </div>    
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control", placeholder: "Endereço de email"%>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :senha %>
      </div>
      <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control", placeholder: "Insira a senha"%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit(@user.new_record? ? "Cadastrar" : "Atualizar dados cadastrais", class: "btn btn-primary btn-lg") %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      <%= link_to 'Cancelar e voltar para os artigos', articles_path, class:"btn btn-primary btn-sm" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Alterar dados cadastrais</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Todos os usuários</h1>
<div align = "center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class = "listing">
      <div class = "row">
        <div class = "well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class = "article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
            <li ><small><%= pluralize(user.articles.count, "artigo") if
            user.articles %></small></li>
            <% if logged_in? and current_user.admin? %>
              <li><%= link_to "Remover esse usuário", user_path(user), method: :delete,
                  data: {confirm: "Você tem certeza disso? Uma vez feito, não poderá ser desfeito."} %></li>
            <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Cadastre-se no alfa blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bem vindo a página do <%= @user.username%>.</h1>
<div class = "row">
  <div class = "col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 120 %>
  </div>
</div>
<h4 align="center"> Artigos escritos por <%= @user.username %>:</h4>

<div class = "center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class = "center">
  <%= will_paginate @user_articles %>
</div>